version: '2.1'

services:
  picture-modal:
    image: picture-modal
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3050:3050
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js